version: "3.9"
services:
  # Front end client
  client:
    image: client
    build:
      dockerfile: Dockerfile
      context: ./client
    depends_on:
    - server
    # optional
    # Exposing these ports will be useful for debugging
    ports:
      - "5040:3000"
  # Backend server
  server:
    image: server
    build:
      dockerfile: Dockerfile
      context: "./server"
      # optional
      # Exposing these ports will be useful for debugging
    ports:
      - "5050:8000"
  # Proxies requests to internal services
  nginx:
    image: nginx
    depends_on:
      - client
      - server
    volumes:
    - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      # external 8080 -> nginx 80
      - 8080:80